### ISSUE TITLE
Podcasts section of open.spotify.com with new header description

### ISSUE THREAD

**Issue by FuncSol** [martin-hamilton/banish-spotify-podcasts#3]
the Podcast section is being shown as the name is changing arbitrarily. 

Currently is "What's trending?"

Does disappear as expected depending on if the text is one of the filtered strings in styles.css
![Screenshot 2022-04-26 112241](https://user-images.githubusercontent.com/42657022/165190268-ec172e3f-d0c2-483e-80f5-dc4ade04c61f.jpg)

**Comment by martin-hamilton** [comment]
Aargh! I've found a couple of other variations in addition to this - have added to GitHub and will resubmit extension for review in a mo. Many thanks for spotting it :-)
